# Generated by Django 2.2.10 on 2020-11-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pdf', models.FileField(upload_to='coure')),
                ('moduleid', models.IntegerField(default=0)),
                ('module', models.CharField(default='module', max_length=150)),
                ('moduleUrl', models.CharField(default='moduleUrl', max_length=150)),
                ('semmester', models.CharField(default='semmester', max_length=150)),
                ('semmesterUrl', models.CharField(default='semmesterUrl', max_length=150)),
                ('semmesterID', models.IntegerField(default=0)),
                ('filier', models.CharField(default='filier', max_length=150)),
                ('filierID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pdf', models.FileField(upload_to='EXAMs')),
                ('moduleid', models.IntegerField(default=0)),
                ('module', models.CharField(default='module', max_length=150)),
                ('moduleUrl', models.CharField(default='moduleUrl', max_length=150)),
                ('semmester', models.CharField(default='semmester', max_length=150)),
                ('semmesterUrl', models.CharField(default='semmesterUrl', max_length=150)),
                ('semmesterID', models.IntegerField(default=0)),
                ('filier', models.CharField(default='filier', max_length=150)),
                ('filierID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Filier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('pic', models.ImageField(blank=True, default='filier.png', null=True, upload_to='filier')),
                ('count', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nameUrl', models.CharField(default='nameUrl', max_length=150)),
                ('nameSem', models.CharField(default='nameSem', max_length=150)),
                ('semmester', models.CharField(default='Semmester', max_length=150)),
                ('semmesterUrl', models.CharField(default='semmesterUrl', max_length=150)),
                ('filier', models.CharField(default='-', max_length=150)),
                ('semmesteriD', models.IntegerField(default=0)),
                ('filieriD', models.IntegerField(default=0)),
                ('ccount', models.IntegerField(default=0)),
                ('Tdcount', models.IntegerField(default=0)),
                ('tpcount', models.IntegerField(default=0)),
                ('ecount', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
                ('Lasshow', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Semmester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('purname', models.CharField(default='purname', max_length=150)),
                ('nameUrl', models.CharField(default='nameUrl', max_length=150)),
                ('filier', models.CharField(default='filier', max_length=150)),
                ('count', models.IntegerField(default=0)),
                ('filierId', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pdf', models.FileField(upload_to='td')),
                ('moduleid', models.IntegerField(default=0)),
                ('module', models.CharField(default='module', max_length=150)),
                ('moduleUrl', models.CharField(default='moduleUrl', max_length=150)),
                ('semmester', models.CharField(default='semmester', max_length=150)),
                ('semmesterUrl', models.CharField(default='semmesterUrl', max_length=150)),
                ('semmesterID', models.IntegerField(default=0)),
                ('filier', models.CharField(default='filier', max_length=150)),
                ('filierID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pdf', models.FileField(upload_to='TPs')),
                ('moduleid', models.IntegerField(default=0)),
                ('module', models.CharField(default='module', max_length=150)),
                ('moduleUrl', models.CharField(default='moduleUrl', max_length=150)),
                ('semmester', models.CharField(default='semmester', max_length=150)),
                ('semmesterUrl', models.CharField(default='semmesterUrl', max_length=150)),
                ('semmesterID', models.IntegerField(default=0)),
                ('filier', models.CharField(default='filier', max_length=150)),
                ('filierID', models.IntegerField(default=0)),
            ],
        ),
    ]
