# Generated by Django 3.1.2 on 2020-10-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filier',
            name='pic',
            field=models.ImageField(blank=True, default='filier.png', null=True, upload_to='filier'),
        ),
    ]
