# Generated by Django 2.2.10 on 2020-11-03 20:53

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=400)),
                ('artID', models.CharField(default='0', max_length=400)),
                ('catID', models.IntegerField(default=0)),
                ('discripton', ckeditor.fields.RichTextField()),
                ('artbody', ckeditor_uploader.fields.RichTextUploadingField()),
                ('pic', models.ImageField(blank=True, default='art.png', null=True, upload_to='Article')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('show', models.IntegerField(default=0)),
                ('act', models.IntegerField(default=0)),
                ('rand', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=400)),
                ('count', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=400)),
                ('artId', models.CharField(default='artId', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=400)),
                ('artId', models.CharField(default='artId', max_length=400)),
                ('link', models.CharField(default='link', max_length=400)),
                ('artname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Cat'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='article.Tags'),
        ),
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
