# Generated by Django 2.2.10 on 2020-10-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20201028_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='artID',
        ),
    ]
