# Generated by Django 2.2.10 on 2020-11-03 20:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiant', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('free', models.BooleanField(default=False)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ecrivain', models.CharField(default='none', max_length=25)),
                ('pic', models.ImageField(blank=True, default='book.png', null=True, upload_to='Books/Image')),
                ('pdf', models.FileField(max_length=200, upload_to='Books/Pdf')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('cat', models.ManyToManyField(blank=True, to='article.Cat')),
                ('filier', models.ManyToManyField(blank=True, to='etudiant.Filier')),
            ],
        ),
    ]
