# Generated by Django 2.2.10 on 2020-11-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
