# Generated by Django 2.2.10 on 2020-11-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_books_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='free',
        ),
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Not_Free', 'Not_Free')], max_length=200, null=True),
        ),
    ]
