# Generated by Django 2.2.10 on 2020-11-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20201104_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.FloatField(blank=True, default='00', null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='show',
            field=models.IntegerField(default=0),
        ),
    ]
